### ISSUE TITLE
Broken on Mac OS X 10.11

### ISSUE THREAD

**Issue by x2on** [chadrem/market_bot#43] opened 2015-10-02 09:27 UTC
On Mac OS X 10.11 the `ffi` library is broken:

```
/usr/local/Cellar/gems/2.0.0/gems/ffi-1.9.6/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'c': dlopen(c, 5): image not found. (LoadError)
Could not open library 'libc.dylib': dlopen(libc.dylib, 5): image not found
	from /usr/local/Cellar/gems/2.0.0/gems/ffi-1.9.6/lib/ffi/library.rb:100:in `map'
	from /usr/local/Cellar/gems/2.0.0/gems/ffi-1.9.6/lib/ffi/library.rb:100:in `ffi_lib'
	from /usr/local/Cellar/gems/2.0.0/gems/ethon-0.7.1/lib/ethon/libc.rb:8:in `<module:Libc>'
	from /usr/local/Cellar/gems/2.0.0/gems/ethon-0.7.1/lib/ethon/libc.rb:6:in `<module:Ethon>'
	from /usr/local/Cellar/gems/2.0.0/gems/ethon-0.7.1/lib/ethon/libc.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/gems/2.0.0/gems/ethon-0.7.1/lib/ethon.rb:10:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/gems/2.0.0/gems/typhoeus-0.6.9/lib/typhoeus.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/gems/2.0.0/gems/market_bot-0.14.0/lib/market_bot.rb:3:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from test.rb:2:in `<main>'
```

See https://github.com/ffi/ffi/issues/461

**Comment by chadrem** [comment] 2015-10-05 20:56
@x2on As you mentioned this appears to be a FFI bug (not a market_bot bug).  I'll leave this issue open until I hear that the FFI bug is resolved.  Thanks for linking to it!

**Comment by x2on** [comment] 2015-11-26 12:04
Adding 
```ruby
gem 'ffi', :git => 'git://github.com/ffi/ffi.git', :branch => 'elcapt'
```
to the `Gemfile` fixes the issue

**Comment by jakanjakan** [comment] 2015-12-01 09:28
@x2on thanks, that solved it.

**Comment by chadrem** [comment] 2016-05-21 00:49
I just tested in the latest updated version of OSX, 10.11.4, with latest market_bot in master, and Typhoeus 1.0.2, and ruby 2.3.1.  I uninstalled marketbot, typhoeus, and ffi gems.  I then installed them via bundler.  I was unable to reproduce this issue so my guess is it is resolved by a fix in one of the dependencies, latest ruby, or an OS update.  Please let me know if you are able to reproduce this issue.  My plan is to close it for now since it has been open for many months and I suspect it's fixed.

**Closed by chadrem** 2016-05-21 00:49 UTC
